# Generated by Django 6.0.2 on 2026-03-09 18:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=16)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('init', 'Init'), ('validate', 'Validate'), ('build', 'Build'), ('postprocess', 'Postprocess'), ('done', 'Done')], default='queued', max_length=16)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('result_payload', models.JSONField(default=dict)),
                ('workspace_path', models.TextField(blank=True)),
                ('log_path', models.TextField(blank=True)),
                ('packer_template_path', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_build_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=128)),
                ('template_vmid', models.CharField(max_length=32)),
                ('target_os', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], max_length=16)),
                ('iso_url', models.URLField(max_length=512)),
                ('iso_filename', models.CharField(blank=True, max_length=255)),
                ('iso_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('hardware', models.JSONField(default=dict)),
                ('network', models.JSONField(default=dict)),
                ('windows_options', models.JSONField(default=dict)),
                ('ansible_options', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.templatebuildjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_definitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='templatebuildjob',
            name='template_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_jobs', to='core.templatedefinition'),
        ),
        migrations.AddIndex(
            model_name='templatedefinition',
            index=models.Index(fields=['owner', 'template_vmid'], name='core_templa_owner_i_69939e_idx'),
        ),
        migrations.AddIndex(
            model_name='templatedefinition',
            index=models.Index(fields=['target_os', 'updated_at'], name='core_templa_target__1e1ba6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatedefinition',
            unique_together={('owner', 'template_vmid')},
        ),
        migrations.AddIndex(
            model_name='templatebuildjob',
            index=models.Index(fields=['status', 'queued_at'], name='core_templa_status_c2c5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='templatebuildjob',
            index=models.Index(fields=['owner', 'created_at'], name='core_templa_owner_i_bc09fb_idx'),
        ),
    ]
