# Generated by Django 6.0.2 on 2026-04-06 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_directoryprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxmox_vmid', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('node', models.CharField(max_length=64)),
                ('hardware', models.JSONField(default=dict)),
                ('network', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('running', 'Running'), ('failed', 'Failed')], default='provisioning', max_length=16)),
                ('task_upid', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='template_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='core.templatedefinition'),
        ),
        migrations.AddIndex(
            model_name='virtualmachine',
            index=models.Index(fields=['owner', 'created_at'], name='core_virtua_owner_i_e00cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmachine',
            index=models.Index(fields=['status', 'updated_at'], name='core_virtua_status_291309_idx'),
        ),
    ]
